Document: capnproto-c++
Title: Debian capnproto-c++ Manual
Author: <insert document author here>
Abstract: This manual describes what capnproto-c++ is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/capnproto-c++/capnproto-c++.sgml.gz

Format: postscript
Files: /usr/share/doc/capnproto-c++/capnproto-c++.ps.gz

Format: text
Files: /usr/share/doc/capnproto-c++/capnproto-c++.text.gz

Format: HTML
Index: /usr/share/doc/capnproto-c++/html/index.html
Files: /usr/share/doc/capnproto-c++/html/*.html
